/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicMarketingRouteImport } from './routes/_public/_marketing'
import { Route as PublicMarketingIndexRouteImport } from './routes/_public/_marketing/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicAuthSignUpIndexRouteImport } from './routes/_public/auth/sign-up/index'
import { Route as PublicAuthSignInIndexRouteImport } from './routes/_public/auth/sign-in/index'
import { Route as PublicMarketingAboutIndexRouteImport } from './routes/_public/_marketing/about/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMarketingRoute = PublicMarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketingIndexRoute = PublicMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicMarketingRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthSignUpIndexRoute = PublicAuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthSignInIndexRoute = PublicAuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketingAboutIndexRoute =
  PublicMarketingAboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => PublicMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicMarketingIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/about/': typeof PublicMarketingAboutIndexRoute
  '/auth/sign-in/': typeof PublicAuthSignInIndexRoute
  '/auth/sign-up/': typeof PublicAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicMarketingIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/about': typeof PublicMarketingAboutIndexRoute
  '/auth/sign-in': typeof PublicAuthSignInIndexRoute
  '/auth/sign-up': typeof PublicAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/_marketing': typeof PublicMarketingRouteWithChildren
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_public/_marketing/': typeof PublicMarketingIndexRoute
  '/_public/_marketing/about/': typeof PublicMarketingAboutIndexRoute
  '/_public/auth/sign-in/': typeof PublicAuthSignInIndexRoute
  '/_public/auth/sign-up/': typeof PublicAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/about/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/about' | '/auth/sign-in' | '/auth/sign-up'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/_marketing'
    | '/_protected/dashboard/'
    | '/_public/_marketing/'
    | '/_public/_marketing/about/'
    | '/_public/auth/sign-in/'
    | '/_public/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_marketing': {
      id: '/_public/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicMarketingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_marketing/': {
      id: '/_public/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicMarketingIndexRouteImport
      parentRoute: typeof PublicMarketingRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/sign-up/': {
      id: '/_public/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof PublicAuthSignUpIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/sign-in/': {
      id: '/_public/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof PublicAuthSignInIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_marketing/about/': {
      id: '/_public/_marketing/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicMarketingAboutIndexRouteImport
      parentRoute: typeof PublicMarketingRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicMarketingRouteChildren {
  PublicMarketingIndexRoute: typeof PublicMarketingIndexRoute
  PublicMarketingAboutIndexRoute: typeof PublicMarketingAboutIndexRoute
}

const PublicMarketingRouteChildren: PublicMarketingRouteChildren = {
  PublicMarketingIndexRoute: PublicMarketingIndexRoute,
  PublicMarketingAboutIndexRoute: PublicMarketingAboutIndexRoute,
}

const PublicMarketingRouteWithChildren = PublicMarketingRoute._addFileChildren(
  PublicMarketingRouteChildren,
)

interface PublicRouteChildren {
  PublicMarketingRoute: typeof PublicMarketingRouteWithChildren
  PublicAuthSignInIndexRoute: typeof PublicAuthSignInIndexRoute
  PublicAuthSignUpIndexRoute: typeof PublicAuthSignUpIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicMarketingRoute: PublicMarketingRouteWithChildren,
  PublicAuthSignInIndexRoute: PublicAuthSignInIndexRoute,
  PublicAuthSignUpIndexRoute: PublicAuthSignUpIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
